version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: quick_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb:27017/quickcommerce
      - JWT_KEY=MYSECRET
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend/quick-commerce
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:5000"  # <-- point to backend container
    container_name: quick_frontend
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
