version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: quick_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/quickcommerce
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/quick-commerce
    container_name: quick_frontend
    restart: always
    ports:
      - "80:80"  # Serve via Nginx on port 80
    depends_on:
      - backend

volumes:
  mongo_data:
